name = "cf-worker-shorturl"
main = "src/index.js"
compatibility_date = "2024-04-16"
node_compat = true

[[kv_namespaces]]
binding = "LINKS"
id = "7876fd741be54100b1179e0d983a9ac7" ## Change it to yours
[build]
command = "npm run build"
[vars]
USERNAME = "marcioluiz" # Change it and don't expose it in this file
PASSWORD = "nuxzt7rtf&3dgzni@u2g" # Change it and don't expose it in this file
JWT_SECRET = "jxhnd3u&8y@7tbddm#uzy23f3" # Change it and don't expose it in this file
DEFAULT_PAGE = "https://marcioluiz.tec.br" # Change it
RECORD_CLICKS = true
FE_ADMIN_DOMAIN = "https://shtr.marcioluiz.tec.br" #Remember to replace it with your admin domain, important for cross origin allowlist


